export enum EventName {
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  PROJECT_STARTED = "PROJECT_STARTED",
  PROJECT_PAUSED = "PROJECT_PAUSED",
  PROJECT_COMPLETED = "PROJECT_COMPLETED",
  PROJECT_CANCELLED = "PROJECT_CANCELLED",
  PROJECT_DEADLINE_UPDATED = "PROJECT_DEADLINE_UPDATED",
  PROJECT_BUDGET_UPDATED = "PROJECT_BUDGET_UPDATED",

  CLIENT_CREATED = "CLIENT_CREATED",
  CLIENT_UPDATED = "CLIENT_UPDATED",
  CLIENT_ARCHIVED = "CLIENT_ARCHIVED",
  CLIENT_BLOCKED = "CLIENT_BLOCKED",

  CLIENT_MESSAGE_RECEIVED = "CLIENT_MESSAGE_RECEIVED",
  CLIENT_MESSAGE_SENT = "CLIENT_MESSAGE_SENT",
  CLIENT_CONVERSATION_UPDATED = "CLIENT_CONVERSATION_UPDATED",
  NEW_REQUIREMENT_DETECTED = "NEW_REQUIREMENT_DETECTED",

  REQUIREMENT_CREATED = "REQUIREMENT_CREATED",
  REQUIREMENT_UPDATED = "REQUIREMENT_UPDATED",
  REQUIREMENT_APPROVED = "REQUIREMENT_APPROVED",
  REQUIREMENT_REJECTED = "REQUIREMENT_REJECTED",

  DEVELOPER_ASSIGNED = "DEVELOPER_ASSIGNED",
  DEVELOPER_UNASSIGNED = "DEVELOPER_UNASSIGNED",
  DEVELOPER_NOTIFIED = "DEVELOPER_NOTIFIED",
  DEVELOPER_PROGRESS_UPDATED = "DEVELOPER_PROGRESS_UPDATED",

  TASK_CREATED = "TASK_CREATED",
  TASK_STARTED = "TASK_STARTED",
  TASK_IN_PROGRESS = "TASK_IN_PROGRESS",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_REOPENED = "TASK_REOPENED",
  TASK_CANCELLED = "TASK_CANCELLED",

  DEADLINE_APPROACHING = "DEADLINE_APPROACHING",
  DEADLINE_MISSED = "DEADLINE_MISSED",
  REMINDER_TRIGGERED = "REMINDER_TRIGGERED",
  FOLLOWUP_REQUIRED = "FOLLOWUP_REQUIRED",

  BUDGET_UPDATED = "BUDGET_UPDATED",
  BUDGET_EXCEEDED = "BUDGET_EXCEEDED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  INVOICE_GENERATED = "INVOICE_GENERATED",

  EMAIL_NOTIFICATION_SENT = "EMAIL_NOTIFICATION_SENT",
  WHATSAPP_NOTIFICATION_SENT = "WHATSAPP_NOTIFICATION_SENT",
  SYSTEM_NOTIFICATION_SENT = "SYSTEM_NOTIFICATION_SENT",

  MEMORY_UPDATED = "MEMORY_UPDATED",
  PROJECT_CONTEXT_LOADED = "PROJECT_CONTEXT_LOADED",
  INTENT_DETECTED = "INTENT_DETECTED",
  RESPONSE_GENERATED = "RESPONSE_GENERATED",
}
